<?php

namespace RutasBundle\Repository;

/**
 * rutaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class rutaRepository extends \Doctrine\ORM\EntityRepository
{
}
